name: Docker Compose Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build and start containers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker compose --env-file docker-compose.env.example -f docker-compose.yml -f docker-compose.ci.yml up --build -d

      - name: Wait for SQL Server to be ready
        run: |
          echo "Waiting for SQL Server..."
          for i in {1..30}; do
            if docker exec sql_server /opt/mssql-tools18/bin/sqlcmd \
              -S localhost -U sa -P "sqlS3cret!" \
              -Q "SELECT 1" -C; then
              echo "SQL Server is ready"
              break
            fi
            sleep 2
          done

      - name: Run tests inside app container
        run: |
          docker exec msi echo "Running tests ..."

      - name: Dump logs on failure
        if: failure()
        run: docker compose logs

      - name: Shutdown containers
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v
